version: "3.8"

services:
  app: &app-service
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    tty: true
    working_dir: /go/src/app
    networks:
      - backend

networks:
  backend:
    driver: bridge